CREATE TABLE worker (
        ID INT PRIMARY KEY,
        NAME VARCHAR(1000) NOT NULL,
        BIRTHDAY DATE CHECK (BIRTHDAY  >='1900-01-01'),
        LEVEL VARCHAR(20) NOT NULL ,
        CONSTRAINT Check_Level CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
        SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE client (
        ID INT PRIMARY KEY,
        NAME VARCHAR(1000) NOT NULL
);

CREATE TABLE project (
    ID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CLIENT_ID INT NOT NULL,
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID),
    START_DATE DATE NOT NULL,
    FINISH_DATE DATE,
    CHECK (
        FINISH_DATE IS NULL OR
        (FINISH_DATE >= START_DATE AND DATEDIFF('MONTH', START_DATE, FINISH_DATE) BETWEEN 1 AND 100)
    )
);


CREATE TABLE project_worker (
        PROJECT_ID INT,
        WORKER_ID INT,
       PRIMARY KEY (PROJECT_ID, WORKER_ID)
);